### ISSUE TITLE
IMDSv2 

### ISSUE THREAD

**Issue by SylvainMartel** [CQEN-QDCE/terraform-aws-indy-node#3]
Verify if there is an impact to disable IMDSv1 and use IMDSv2(there shouldn't be any problem) as this can be related to the weaponization phase of kill chain

**Comment by WadeBarnes** [comment]
Addressed with https://github.com/CQEN-QDCE/terraform-aws-indy-node/pull/4 and https://github.com/CQEN-QDCE/Candy/pull/46

**Comment by SylvainMartel** [comment]
Closed by PR #4
